### ISSUE TITLE
Add --keep_going flag

### ISSUE THREAD

**Issue by amit-mittal** [bazel-contrib/target-determinator#39]
While trying to use the `target-determinator` in our repo, I am seeing an error that is not letting me use the tool. 

Can we please add support for `--keep_going` flag to the `bazel query` command, so we don't have to fix all the errors before this tool can actually be used?

**Comment by illicitonion** [comment]
Thanks for trying out `target-determinator` and providing this feedback!

I think it makes sense to expose a `--bazel-opts` flag, just like `--bazel-startup-opts` to allow specifying your own flags.

I don't think we should specially add support for `--keep_going`, because target-determinator aims to be "always correct", and definitely can't guarantee correctness in the face of query errors.

But adding the ability for users to specify their own flags makes sense - I can put together a PR doing this soon.

**Comment by amit-mittal** [comment]
Thanks for the prompt response! That makes sense. I'll try it again as soon as the change is in.

**Comment by illicitonion** [comment]
I've released this flag as v0.15.0: https://github.com/bazel-contrib/target-determinator/releases/tag/v0.15.0
